yarnPath: .yarn/releases/yarn-3.4.1.cjs

# This will allow to install files to node_modules/ for Prettier
# It would be awsome if Prettier can work with yarn 2+ in future
nodeLinker: node-modules
